sudo: required
services:
    - docker
    
before_install:
    - docker build -t anujap/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run anujap/react-test npm test -- --coverage

after_success:
    - docker build -t anujap/multi-client ./client
    - docker build -t anujap/multi-nginx ./nginx
    - docker build -t anujap/multi-server ./server
    - docker build -t anujap/multi-worker ./worker

# Log in to docker CLI
    - echo "$DOCKER-PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    
# Take prod images and push to docker hub


